### ISSUE TITLE
Parse DFoundationsModel results in an AttributeError: type object 'list' has no attribute '_special'

### ISSUE THREAD

**Issue by RDWimmers** [Deltares/GEOLib#8]
When parsing a DFoundations result file with the GEOLib I get an AttributeError. I attach the file to this issue. The file is created with the correct version, as stated in the documentation.

### Steps to reproduce
```
!pip install d-geolib==0.1.6

from geolib import DFoundationsModel

ds = DFoundationsModel()
ds.parse(file)
```

### Relevant logs and/or screenshots
```
File /opt/conda/lib/python3.9/site-packages/geolib/models/base_model.py:149, in BaseModel.parse(self, filename)
    147 self.filename = filename
    148 # self.datastructure = None
--> 149 self.datastructure = self.parser_provider_type().parse(filename)
    150 return self.datastructure

File /opt/conda/lib/python3.9/site-packages/geolib/models/parsers.py:61, in BaseParserProvider.parse(self, filename)
     59 for parser in self.output_parsers:
     60     if parser.can_parse(filename):
---> 61         return parser.parse(filename)
     62 raise ValueError(f"Unknown extension {filename.suffix} for {self.parser_name}.")

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:1147, in DSerieParser.parse(self, filename)
   1144 logger.debug(f"Parsing {filename}")
   1146 with open(filename) as io:
-> 1147     datastructure = self.dserie_structure.parse_text(io.read())
   1149 return datastructure

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:158, in DSeriesStructure.parse_text(cls, data)
    152 """Creates a DSeriesStructure using the concrete parser.
    153 
    154 Arguments:
    155     data {str} -- Data to parse.
    156 """
    157 parsed_structure = DSerieParser.parse_group_as_dict(data)
--> 158 return cls(**parsed_structure)

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:98, in DSeriesStructure.__init__(self, *args, **kwargs)
     96 if hasattr(fieldtype, "is_parseable") and fieldtype.is_parseable():
     97     logger.debug(f"Changed {field} to {fieldtype}")
---> 98     kwargs[field] = fieldtype.parse_text(body)
     99 else:
    100     if DataClass in fieldtype.__mro__:

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:158, in DSeriesStructure.parse_text(cls, data)
    152 """Creates a DSeriesStructure using the concrete parser.
    153 
    154 Arguments:
    155     data {str} -- Data to parse.
    156 """
    157 parsed_structure = DSerieParser.parse_group_as_dict(data)
--> 158 return cls(**parsed_structure)

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:98, in DSeriesStructure.__init__(self, *args, **kwargs)
     96 if hasattr(fieldtype, "is_parseable") and fieldtype.is_parseable():
     97     logger.debug(f"Changed {field} to {fieldtype}")
---> 98     kwargs[field] = fieldtype.parse_text(body)
     99 else:
    100     if DataClass in fieldtype.__mro__:

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:158, in DSeriesStructure.parse_text(cls, data)
    152 """Creates a DSeriesStructure using the concrete parser.
    153 
    154 Arguments:
    155     data {str} -- Data to parse.
    156 """
    157 parsed_structure = DSerieParser.parse_group_as_dict(data)
--> 158 return cls(**parsed_structure)

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:98, in DSeriesStructure.__init__(self, *args, **kwargs)
     96 if hasattr(fieldtype, "is_parseable") and fieldtype.is_parseable():
     97     logger.debug(f"Changed {field} to {fieldtype}")
---> 98     kwargs[field] = fieldtype.parse_text(body)
     99 else:
    100     if DataClass in fieldtype.__mro__:

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:701, in DSeriesStructureCollection.parse_text(cls, text)
    696     raise ValueError(
    697         f"Expected {number_of_groups} groups, but parsed {len(parsed_groups)}."
    698     )
    700 parsed_collection = {fields[0][0]: parsed_groups}
--> 701 return cls(**parsed_collection)

File /opt/conda/lib/python3.9/site-packages/geolib/models/dseries_parser.py:119, in DSeriesStructure.__init__(self, *args, **kwargs)
    117 # And then the list
    118 if is_list(fieldtype):
--> 119     fieldtype, *_ = get_args(fieldtype)
    121     # Check whether we can parse and if so, parse the strings
    122     if hasattr(fieldtype, "is_parseable") and fieldtype.is_parseable():

File /opt/conda/lib/python3.9/site-packages/geolib/models/utils.py:16, in get_args(tp)
      6 def get_args(tp):
      7     """Get type arguments with all substitutions performed.
      8     For unions, basic simplifications used by Union constructor are performed.
      9     Examples::
   (...)
     14         get_args(Callable[[], T][int]) == ([], int)
     15     """
---> 16     if isinstance(tp, (_GenericAlias, _SpecialForm)) and not tp._special:
     17         res = tp.__args__
     18         if tp.__origin__ is collections.abc.Callable and res[0] is not Ellipsis:

File /opt/conda/lib/python3.9/typing.py:705, in _BaseGenericAlias.__getattr__(self, attr)
    701 def __getattr__(self, attr):
    702     # We are careful for copy and pickle.
    703     # Also for simplicity we just don't relay all dunder names
    704     if '__origin__' in self.__dict__ and not _is_dunder(attr):
--> 705         return getattr(self.__origin__, attr)
    706     raise AttributeError(attr)

AttributeError: type object 'list' has no attribute '_special'
```

## File
[bm1-1a.zip](https://github.com/Deltares/GEOLib/files/8495754/bm1-1a.zip)

FYI: @martinapippi

**Comment by evetion** [comment]
This was introduced by https://github.com/Deltares/GEOLib/pull/4

**Comment by yurnih** [comment]
This was fixed by #4. We got the same issue, The pip package didn't include the latest fixes;

See also in commit at line 16, conform the error:
https://github.com/Deltares/GEOLib/pull/4/files#diff-b52ae9887e433905a74de332acd9dc24cc3a33366a073f7a70554d98d7aa2dfaL16-L21

**Comment by evetion** [comment]
Ah, sorry I got it inversed. Closing 👍🏻
